#!/bin/sh

# export DJANGO_SECRET_KEY=
# export DJANGO_RECAPTCHA_SECRET_KEY=

# export MONGODB_SUGUVOTE_HOST=localhost
# export MONGODB_SUGUVOTE_PORT=27017
# export MONGODB_SUGUVOTE_DB_NAME=suguvote
# export MONGODB_SUGUVOTE_USERNAME=
# export MONGODB_SUGUVOTE_PASSWORD=
# export MONGODB_SUGUVOTE_USING_AUTH=True

# export MARIADB_SUGUVOTE_USERNAME=
# export MARIADB_SUGUVOTE_PASSWORD=

# export DJANGO_DEBUG=False